language: cpp


matrix:
  fast_finish: true
  include:
    - os: linux
      env: TOOLSET=clang-3.4
      addons: &clang34
        apt:
          packages:
            - clang-3.4
            - libstdc++-5-dev
            - valgrind
            - gdb
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.4

    - os: linux
      env: TOOLSET=clang-3.5
      addons: &clang35
        apt:
          packages:
            - clang-3.5
            - libstdc++-5-dev
            - valgrind
            - gdb
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.5

    - os: linux
      env: TOOLSET=clang-3.6
      addons: &clang36
        apt:
          packages:
            - clang-3.6
            - libstdc++-5-dev
            - valgrind
            - gdb
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.6

    - os: linux
      env: TOOLSET=clang-3.7
      addons: &clang37
        apt:
          packages:
            - clang-3.7
            - libstdc++-5-dev
            - valgrind
            - gdb
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise

    - os: linux
      env: TOOLSET=gcc-5
      addons: &gcc5
        apt:
          packages:
            - g++-5
            - libstdc++-5-dev
            - valgrind
            - gdb
          sources:
            - ubuntu-toolchain-r-test


#compiler:
#  - gcc

before_install:
#  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
#  - sudo apt-get update -qq
#  - if [ "$CXX" = "g++" ]; then sudo apt-get install -qq g++-4.9; fi
#  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.9" CC="gcc-4.9"; fi
  - sudo pip install cpp-coveralls pyyaml
  - sudo apt-get install valgrind
  - sudo pip install codecov

script:
  - make
  - ./json_unit "*"
  - valgrind --error-exitcode=1 --leak-check=full ./json_unit

after_success:
  - make clean
  - touch src/json.hpp
  - make json_unit CXXFLAGS="-fprofile-arcs -ftest-coverage -std=c++11"
  - ./json_unit "*"
  - coveralls --exclude test/catch.hpp --exclude test/unit.cpp --include src/json.hpp --gcov-options '\-lp' --gcov 'gcov-4.9'
  - codecov
