language: cpp

compiler:
  - gcc

before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -qq
  - if [ "$CXX" = "g++" ]; then sudo apt-get install -qq g++-4.9; fi
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.9" CC="gcc-4.9"; fi
  - sudo pip install cpp-coveralls pyyaml
  - sudo apt-get install valgrind

script:
  - make
  - ./json_unit "*"
  - valgrind --error-exitcode=1 --leak-check=full ./json_unit

after_success:
  - make clean
  - touch src/json.hpp
  - make json_unit CXXFLAGS="-fprofile-arcs -ftest-coverage -std=c++11"
  - ./json_unit "*"
  - coveralls --exclude test/catch.hpp --exclude test/unit.cpp --include src/json.hpp --gcov-options '\-lp' --gcov 'gcov-4.9'

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "kzVz6s9W/rAs3e9nK5cU1vSXkNG0Kqe0g/WHybXNFVkiNTE/eauKgpcxc9QPnPVsLZmS9knANnf3V1/i/u50uYwrmf6ntlka67sXBiACnaYqUsGZ07F0i3evL84OsY/ViXmJ60AbcNDtCJR9oepAH7ANGHLL8z6yX4/m+Ocaj6s="

addons:
  coverity_scan:
    project:
      name: "nlohmann/json"
      description: "Build submitted via Travis CI"
    notification_email: niels.lohmann@gmail.com
    build_command_prepend: "make clean"
    build_command:   "make"
