language: cpp

sudo: false

compiler:
  - gcc

env:
  - COMPILER=g++-4.9
  - COMPILER=g++-5
  - COMPILER=clang-3.4
  - COMPILER=clang-3.5
  - COMPILER=clang-3.6
  - COMPILER=clang-3.7

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - llvm-toolchain-precise
    packages:
    - g++-4.8
    - g++-4.9
    - g++-5
    - clang-3.4
    - clang-3.5
    - clang-3.6
    - clang-3.7
    - valgrind
    - python-pip
    - python-yaml

before_script:
  - pip install --user git+git://github.com/eddyxu/cpp-coveralls.git

script:
  - make CXX=$COMPILER
  - ./json_unit "*"
  - valgrind --error-exitcode=1 --leak-check=full ./json_unit

after_success:
  - make clean
  - touch src/json.hpp
  - make json_unit CXXFLAGS="-fprofile-arcs -ftest-coverage -std=c++11" CXX=$COMPILER
  - ./json_unit "*"
  - coveralls --exclude test/catch.hpp --exclude test/unit.cpp --include src/json.hpp --gcov-options '\-lp' --gcov 'gcov-4.9'
