version: '{build}'
os: Visual Studio 2015 RC
init: []
install: []
build_script:
- set PATH=C:\Program Files (x86)\MSBuild\14.0\Bin;%PATH%
- cmake .
- msbuild json.sln
test_script:
- Debug\json_unit.exe
