version: '{build}'

configuration:
  - Debug
  - Release

os: 
  - Visual Studio 2015
  - Visual Studio 2017

init: []

install: []

build_script:
  - IF "%APPVEYOR_BUILD_WORKER_IMAGE%" == "Visual Studio 2015" ( SET GEN="Visual Studio 14 2015") ELSE (SET GEN="Visual Studio 15 2017")
  - cmake . -G%GEN% 
  - cmake --build . --config Release

test_script:
  - ctest -C Release -V
